# running interactively, then:
if [ "$PS1" ]; then
  alias cl='rlwrap sbcl'
  alias cp='cp -iv'
  alias df='pydf -h'
  alias dns='nmcli dev show | grep DNS'
  alias fixdirs='find . -type d -exec chmod 775 {} \;'
  alias fixfiles='find . -type f -exec chmod 664 {} \;'
  alias ga='git add .'
  alias hello='tmux new-session -A -s hello'
  alias home='ssh -X -p 2222 hillsboro'
  alias info='info --vi-keys'
  alias m='manage.py'
  alias mahna='ssh old.mahnamahna.net'
  alias mv='mv -iv'
  alias more='less'
  alias npmls='npm list --depth=0 2>/dev/null'
  alias o='xdg-open'
  alias pgshell='sudo -u postgres psql'
  alias pc='ssh -X -p 2222 pc'
  alias rm='rm -iv'
  alias rs='manage.py runserver_plus --keep-meta-shutdown'
  alias samson='ssh -X samson'
  alias sources="grep -r --include '*.list' '^deb ' /etc/apt/sources.list /etc/apt/sources.list.d/"
  alias topcmds="history | awk '{print \$2}' | sort | uniq -c | sort -rn | head -20"
  alias ts='du -h --max-depth=1 | sort -h'
  alias weekly='rsync -ax --delete --xattrs /home/matthewn/working/ /media/matthewn/BKUPMN/working/'
  alias x='chmod u+x'
  alias ytmp3='youtube-dl --extract-audio --audio-format mp3'
fi
